@startuml adapter_extends

title 継承パターン

interface Target {
  targetMethod1()
  targetMethod2()
}

class Adapter {
  targetMethod1()
  targetMethod2()
}

class Adaptee {
  methodA()
  methodB()
  methodC()
}

Target <|.. Adapter
Adaptee <|-- Adapter

@enduml